## Estadistica Aplicada
Seccion 2 - 11 agosto 

Francisco Humberto Villegas Reyna 1731722 Grupo:43

In [2]:
7>5
7>10

False

In [3]:
7>10 & 7>5

False

## Lista
Una lista en python es un coleccion de objetos(mismo tipo o distinto tipo) 

NombreLista=[objeto1,objeto2, objeto3, etc]

In [4]:
alumno1=['Francisco','Villegas','23']

In [6]:
type(alumno1)

list

In [7]:
estadistica_g43=['Francisco','Juan','Andrea','Ana']

In [8]:
estadistica_g43[1]

'Juan'

## para escoger un nombre de la lista se debe agregar su posicion pero se empieza desde 0 en esta caso 0,1,2,3

In [12]:
## ana se da de baja de la materia

estadistica_g43.remove('Ana')

In [13]:
estadistica_g43

['Francisco', 'Juan', 'Andrea']

In [14]:
estadistica_g43.append('Jorge')

In [15]:
estadistica_g43

['Francisco', 'Juan', 'Andrea', 'Jorge']

In [16]:
yo_enFCFM=['Francisco','Actuaria',7,70]

In [17]:
yo_enFCFM

['Francisco', 'Actuaria', 7, 70]

In [19]:
mi_carrera=yo_enFCFM[1]
mi_promedio=yo_enFCFM[3]

In [20]:
print('yo estudio en ',mi_carrera, 'y tengo un promedio de ',mi_promedio)

yo estudio en  Actuaria y tengo un promedio de  70


## Librerías/Paquetes/Modulos

Una librería en pyhton, es un conjunto de codigos que le indican a python como hacer determinadas cosas


Para poder usar una librería : primero hayq que instalarla (una vez)y segundo hay que decirle a pyhton que la use

In [23]:
# instalar una libreria de yahoo finanzas!
!pip install yfinance

In [24]:
import yfinance

In [26]:
import yfinance as yahoo

In [27]:
## Numpy

La estructura basica de numpy son los areglos(arryas). Un arreglo es una coleccion de objetos del mismo tipo

Vamos a suponer que sabemos cuantas botellas de agua venden en la cafeteria .Lunes 28, martes 33, miercoles 44, jueves 40, viernes 31


In [28]:
ventas=[28,33,44,40,31]

In [29]:
type(ventas)

list

In [30]:
#use numpy

import numpy as np

In [31]:
ventas=np.array(ventas)

In [32]:
type(ventas)

numpy.ndarray

In [34]:
## sumar
np.sum(ventas)

176

In [36]:
print('las ventas totales de la semana son ', np.sum(ventas), 'botellas de agua'
      )

las ventas totales de la semana son  176 botellas de agua


In [39]:
##multiplicar
np.prod(ventas)

50413440

In [40]:
##valor maximo
np.max(ventas)

44

In [41]:
##valor minimo
np.min(ventas)

28

In [42]:
##ordenar
np.sort(ventas)

array([28, 31, 33, 40, 44])

In [43]:
##media
np.mean(ventas)

35.2

In [44]:
## varianza pobracional
np.var(ventas,ddof=0)

34.959999999999994

In [47]:
## desviacion poblacional 
np.std(ventas)

5.912698199637792

In [49]:
## varianza muestral
np.var(ventas,ddof=1)

43.699999999999996

In [50]:
## desviacion muestral 
np.std(ventas,ddof=1)

6.6105975524153635

In [52]:
## vectores
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
np.arange(0,100, 15)

array([ 0, 15, 30, 45, 60, 75, 90])

In [64]:
##aleatorios de una distribucion uniforme
#semilla
np.random.seed(12)
aleatorios=np.random.randint(0,15,10)

In [65]:
aleatorios

array([11, 11,  6, 13,  1,  2,  3,  3, 12,  0])

In [67]:
aleatorios=np.sort(aleatorios)

In [68]:
aleatorios

array([ 0,  1,  2,  3,  3,  6, 11, 11, 12, 13])

In [69]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [73]:
np.full(6,8)

array([8, 8, 8, 8, 8, 8])

In [75]:
list=[30,24,60]
list=np.array(list)
np.prod(list)

43200

funcion vs metodo

In [77]:
numeros=[1.4567,4.568,10.375]

1 arreglo
2 calcular la media 
3 redondear a dos decimales

In [78]:
np.array(numeros)

array([ 1.4567,  4.568 , 10.375 ])

In [79]:
#media
np.mean(np.array(numeros))

5.466566666666666

In [83]:
##redondear
##funcion
round(np.mean(np.array(numeros)),2)

5.47

In [84]:
#metodo 
np.array(numeros).mean().round(2)

5.47